/**
 * Autora 3D's tools, as the agent sees them: one `cad_*` tool for every call the modeller declares.
 *
 * GENERATED by scripts/sync-autora-3d.mjs from autora-3d/src/core/tools.ts -- do not edit by hand.
 * (`export` is not here: it is `cad_export`, in server/caddesk.ts, because only the server can put the file somewhere.)
 */

import type { ToolSpec } from "../tools";

export const cadSPECS: ToolSpec[] = [
  {
    "name": "cad_scene_get",
    "group": "files",
    "description": "List every shape in the model with its id, name, size, position, material, bevels, group and repeat, plus groups and the overall bounding box. Start here. Axes: x to the right, y away from the front, z up; all in millimetres. A shape stands on its \"bottom\" z and rises to its \"top\".",
    "parameters": {
      "type": "object",
      "properties": {
        "includeCopies": {
          "type": "boolean",
          "description": "Also list the copies a live repeat makes (hidden by default; they follow their source)."
        }
      },
      "required": []
    }
  },
  {
    "name": "cad_shape_get",
    "group": "files",
    "description": "Everything about one shape: its summary, raw outline, faces and edges.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_shape_faces",
    "group": "files",
    "description": "The faces of a shape (top, bottom, each wall) with how to name them in commands, which way each wall faces, and its measurement.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_shape_edges",
    "group": "files",
    "description": "The bevel-able edges of a shape (top/bottom rims by index, vertical corners), with their length and any bevel.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_shape_measure",
    "group": "files",
    "description": "Build the real solid (bevels and all) and report its volume (mm³), surface area, triangle count and whether it is watertight (printable). Slower than the others.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_shape_add",
    "group": "files",
    "description": "Add a stock shape: box, roundedBox, cylinder, triangle, wedge, pentagon, hexagon, octagon or star. It is centred at x,y (default: beside the existing shapes), stands on elevation (default 0, the ground) and rises height mm. With onTopOf it sits on top of that shape.",
    "parameters": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "box",
            "roundedBox",
            "cylinder",
            "triangle",
            "wedge",
            "pentagon",
            "hexagon",
            "octagon",
            "star"
          ]
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "width": {
          "type": "number",
          "description": "Size along x, mm (default 60)."
        },
        "depth": {
          "type": "number",
          "description": "Size along y, mm (default: same as width for round and regular shapes, else 60)."
        },
        "height": {
          "type": "number",
          "description": "Default 40."
        },
        "elevation": {
          "type": "number",
          "description": "Height of its underside above the ground."
        },
        "onTopOf": {
          "type": "string",
          "description": "Id of a shape to sit on."
        },
        "name": {
          "type": "string"
        },
        "color": {
          "type": "string",
          "description": "Hex colour such as \"#3b82f6\"."
        },
        "material": {
          "type": "string",
          "enum": [
            "matte",
            "metal",
            "glossy",
            "glass",
            "neon"
          ]
        }
      },
      "required": [
        "kind"
      ]
    }
  },
  {
    "name": "cad_shape_draw",
    "group": "files",
    "description": "Sketch an outline (polygon with optional curved sides, rectangle or circle) on a surface and extrude it into a new shape (default 20 mm). On a wall the shape grows out of the wall.",
    "parameters": {
      "type": "object",
      "properties": {
        "form": {
          "type": "string",
          "enum": [
            "polygon",
            "rectangle",
            "circle"
          ]
        },
        "points": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y"
            ],
            "description": "A point on the ground plane, mm."
          },
          "minItems": 3,
          "description": "polygon: the corners in order."
        },
        "bends": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "x": {
                    "type": "number"
                  },
                  "y": {
                    "type": "number"
                  }
                },
                "required": [
                  "x",
                  "y"
                ],
                "description": "A point on the ground plane, mm."
              },
              {
                "type": "null"
              }
            ]
          },
          "description": "polygon: for each side (corner i to corner i+1, the last closes the shape) a point the side passes through, making it a curve; null keeps it straight."
        },
        "from": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "rectangle: one corner."
        },
        "to": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "rectangle: the opposite corner."
        },
        "center": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "circle: its centre."
        },
        "radius": {
          "type": "number",
          "description": "circle: radius, mm."
        },
        "surface": {
          "description": "Where to draw. \"ground\" (default); {\"topOf\": id} the top face of a shape; {\"z\": mm} a horizontal plane at a height; or {\"wallOf\": id, \"wall\": index, \"along\"?: mm, \"up\"?: mm} one of its walls (the sketch then lies in the wall: x runs to the right as you face it, y runs up, both from the middle of the wall; \"along\"/\"up\" shift that origin).",
          "oneOf": [
            {
              "type": "string",
              "enum": [
                "ground"
              ]
            },
            {
              "type": "object",
              "properties": {
                "topOf": {
                  "type": "string"
                }
              },
              "required": [
                "topOf"
              ]
            },
            {
              "type": "object",
              "properties": {
                "z": {
                  "type": "number"
                }
              },
              "required": [
                "z"
              ]
            },
            {
              "type": "object",
              "properties": {
                "wallOf": {
                  "type": "string"
                },
                "wall": {
                  "type": "integer"
                },
                "along": {
                  "type": "number"
                },
                "up": {
                  "type": "number"
                }
              },
              "required": [
                "wallOf",
                "wall"
              ]
            }
          ]
        },
        "height": {
          "type": "number",
          "description": "How far it extrudes, mm (default 20). On a wall: out from the wall."
        },
        "name": {
          "type": "string"
        },
        "color": {
          "type": "string",
          "description": "Hex colour such as \"#3b82f6\"."
        },
        "material": {
          "type": "string",
          "enum": [
            "matte",
            "metal",
            "glossy",
            "glass",
            "neon"
          ]
        }
      },
      "required": [
        "form"
      ]
    }
  },
  {
    "name": "cad_shape_cut",
    "group": "files",
    "description": "Cut a hole or pocket into a shape: sketch an outline on its top face and cut it down by depth mm (or all the way through when depth is omitted). Upright shapes only.",
    "parameters": {
      "type": "object",
      "properties": {
        "target": {
          "type": "string"
        },
        "form": {
          "type": "string",
          "enum": [
            "polygon",
            "rectangle",
            "circle"
          ]
        },
        "points": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y"
            ],
            "description": "A point on the ground plane, mm."
          },
          "minItems": 3,
          "description": "polygon: the corners in order."
        },
        "bends": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "x": {
                    "type": "number"
                  },
                  "y": {
                    "type": "number"
                  }
                },
                "required": [
                  "x",
                  "y"
                ],
                "description": "A point on the ground plane, mm."
              },
              {
                "type": "null"
              }
            ]
          },
          "description": "polygon: for each side (corner i to corner i+1, the last closes the shape) a point the side passes through, making it a curve; null keeps it straight."
        },
        "from": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "rectangle: one corner."
        },
        "to": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "rectangle: the opposite corner."
        },
        "center": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "circle: its centre."
        },
        "radius": {
          "type": "number",
          "description": "circle: radius, mm."
        },
        "surface": {
          "description": "Where to draw. \"ground\" (default); {\"topOf\": id} the top face of a shape; {\"z\": mm} a horizontal plane at a height; or {\"wallOf\": id, \"wall\": index, \"along\"?: mm, \"up\"?: mm} one of its walls (the sketch then lies in the wall: x runs to the right as you face it, y runs up, both from the middle of the wall; \"along\"/\"up\" shift that origin).",
          "oneOf": [
            {
              "type": "string",
              "enum": [
                "ground"
              ]
            },
            {
              "type": "object",
              "properties": {
                "topOf": {
                  "type": "string"
                }
              },
              "required": [
                "topOf"
              ]
            },
            {
              "type": "object",
              "properties": {
                "z": {
                  "type": "number"
                }
              },
              "required": [
                "z"
              ]
            },
            {
              "type": "object",
              "properties": {
                "wallOf": {
                  "type": "string"
                },
                "wall": {
                  "type": "integer"
                },
                "along": {
                  "type": "number"
                },
                "up": {
                  "type": "number"
                }
              },
              "required": [
                "wallOf",
                "wall"
              ]
            }
          ]
        },
        "depth": {
          "type": "number"
        }
      },
      "required": [
        "target",
        "form"
      ]
    }
  },
  {
    "name": "cad_shape_set",
    "group": "files",
    "description": "Change a shape: name, colour, material, visibility, height, elevation (its underside), one radius for all vertical corners, or replace its outline with new corner points (this clears its holes and bevels).",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "color": {
          "type": "string",
          "description": "Hex colour such as \"#3b82f6\"."
        },
        "material": {
          "type": "string",
          "enum": [
            "matte",
            "metal",
            "glossy",
            "glass",
            "neon"
          ]
        },
        "visible": {
          "type": "boolean"
        },
        "height": {
          "type": "number"
        },
        "elevation": {
          "type": "number"
        },
        "cornerRadius": {
          "type": "number"
        },
        "outline": {
          "type": "object",
          "properties": {
            "points": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "x": {
                    "type": "number"
                  },
                  "y": {
                    "type": "number"
                  }
                },
                "required": [
                  "x",
                  "y"
                ],
                "description": "A point on the ground plane, mm."
              },
              "minItems": 3
            },
            "cornerRadii": {
              "type": "array",
              "items": {
                "type": "number"
              }
            }
          },
          "required": [
            "points"
          ]
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_shape_move",
    "group": "files",
    "description": "Move shapes (and their group-mates; a live repeat's path goes with its shape). Either by an offset, or to a place: footprint centre x,y and underside z.",
    "parameters": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        },
        "by": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            },
            "z": {
              "type": "number"
            }
          },
          "required": []
        },
        "to": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            },
            "z": {
              "type": "number"
            }
          },
          "required": []
        }
      },
      "required": [
        "ids"
      ]
    }
  },
  {
    "name": "cad_shape_turn",
    "group": "files",
    "description": "Turn shapes about the vertical axis. Positive degrees turn counter-clockwise seen from above. Default pivot: the centre of the shapes.",
    "parameters": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        },
        "degrees": {
          "type": "number"
        },
        "about": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "A point on the ground plane, mm."
        }
      },
      "required": [
        "ids",
        "degrees"
      ]
    }
  },
  {
    "name": "cad_shape_resize",
    "group": "files",
    "description": "Set a shape's overall width (x), depth (y) and/or height (z). Corners and bevels stay valid.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "depth": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_face_set",
    "group": "files",
    "description": "Type a number for a face, as a person would: set the height (top/bottom) or the size across a wall. The shape grows or shrinks to match.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "face": {
          "description": "A face: \"top\", \"bottom\", or {\"kind\":\"wall\",\"index\":n}. cad_shape_faces lists them with their indices.",
          "oneOf": [
            {
              "type": "string",
              "enum": [
                "top",
                "bottom"
              ]
            },
            {
              "type": "object",
              "properties": {
                "kind": {
                  "const": "wall"
                },
                "index": {
                  "type": "integer"
                }
              },
              "required": [
                "kind",
                "index"
              ]
            }
          ]
        },
        "value": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "face",
        "value"
      ]
    }
  },
  {
    "name": "cad_face_push",
    "group": "files",
    "description": "Push or pull a face by a distance (positive pulls it outward, negative pushes it in).",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "face": {
          "description": "A face: \"top\", \"bottom\", or {\"kind\":\"wall\",\"index\":n}. cad_shape_faces lists them with their indices.",
          "oneOf": [
            {
              "type": "string",
              "enum": [
                "top",
                "bottom"
              ]
            },
            {
              "type": "object",
              "properties": {
                "kind": {
                  "const": "wall"
                },
                "index": {
                  "type": "integer"
                }
              },
              "required": [
                "kind",
                "index"
              ]
            }
          ]
        },
        "by": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "face",
        "by"
      ]
    }
  },
  {
    "name": "cad_edge_bevel",
    "group": "files",
    "description": "Bevel edges: curved (\"round\") or flat (\"chamfer\"). Choose edges by list, by group (top, bottom, corner = vertical corners, all) or every edge around a face. size 0 removes the bevel; for vertical corners size is the corner radius. Sizes are held to what the shape allows; the result reports the size you got.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "edges": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string",
                "enum": [
                  "top",
                  "bottom",
                  "corner"
                ]
              },
              "index": {
                "type": "integer"
              }
            },
            "required": [
              "kind",
              "index"
            ]
          }
        },
        "group": {
          "type": "string",
          "enum": [
            "top",
            "bottom",
            "corner",
            "all"
          ]
        },
        "aroundFace": {
          "description": "A face: \"top\", \"bottom\", or {\"kind\":\"wall\",\"index\":n}. cad_shape_faces lists them with their indices.",
          "oneOf": [
            {
              "type": "string",
              "enum": [
                "top",
                "bottom"
              ]
            },
            {
              "type": "object",
              "properties": {
                "kind": {
                  "const": "wall"
                },
                "index": {
                  "type": "integer"
                }
              },
              "required": [
                "kind",
                "index"
              ]
            }
          ]
        },
        "size": {
          "type": "number"
        },
        "style": {
          "type": "string",
          "enum": [
            "round",
            "chamfer"
          ]
        }
      },
      "required": [
        "id",
        "size"
      ]
    }
  },
  {
    "name": "cad_shape_delete",
    "group": "files",
    "description": "Delete shapes (and their group-mates, and the copies of their live repeats).",
    "parameters": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        }
      },
      "required": [
        "ids"
      ]
    }
  },
  {
    "name": "cad_shape_duplicate",
    "group": "files",
    "description": "Duplicate shapes, offset by (35, −35) mm unless by is given.",
    "parameters": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        },
        "by": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": []
        }
      },
      "required": [
        "ids"
      ]
    }
  },
  {
    "name": "cad_group_create",
    "group": "files",
    "description": "Group shapes so they select, move and turn together, and give the group a name (it becomes the object name in GLB export). Groups nest: a group that is wholly inside the ids is put inside the new one, so group \"head\" + \"body\" makes one \"character\".",
    "parameters": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "ids"
      ]
    }
  },
  {
    "name": "cad_group_rename",
    "group": "files",
    "description": "Rename a group (e.g. \"head\"). Find group ids with cad_scene_get.",
    "parameters": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "group",
        "name"
      ]
    }
  },
  {
    "name": "cad_library_list",
    "group": "files",
    "description": "The project library: reusable objects with their size and how many linked copies are placed.",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "cad_library_save",
    "group": "files",
    "description": "Save a group (or one ungrouped shape) to the project library under its name. It stays in the scene as the first linked copy. If the group was opened with cad_object_unlink it updates its library object instead, and every linked copy follows.",
    "parameters": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "description": "A single ungrouped shape, when there is no group."
        },
        "name": {
          "type": "string"
        }
      },
      "required": []
    }
  },
  {
    "name": "cad_library_place",
    "group": "files",
    "description": "Place a linked copy of a library object (default: beside the scene; or on top of a shape). A linked copy moves, turns and deletes as one piece and follows its library object; to change the object use cad_object_unlink then cad_library_save.",
    "parameters": {
      "type": "object",
      "properties": {
        "item": {
          "type": "string"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        },
        "angle": {
          "type": "number",
          "description": "Degrees, counter-clockwise from above."
        },
        "onTopOf": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "item"
      ]
    }
  },
  {
    "name": "cad_object_unlink",
    "group": "files",
    "description": "Open a linked copy for editing: its shapes become ordinary, you edit them, then cad_library_save the group to update the library object (all copies follow). With forget:true it becomes separate shapes for good.",
    "parameters": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "forget": {
          "type": "boolean"
        }
      },
      "required": [
        "group"
      ]
    }
  },
  {
    "name": "cad_library_thumbnail",
    "group": "files",
    "description": "A small picture of a library object (or of a shape group in the scene via `shapes`) as SVG text: isometric, coloured, no GL needed.",
    "parameters": {
      "type": "object",
      "properties": {
        "item": {
          "type": "string"
        },
        "shapes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "size": {
          "type": "number",
          "description": "Pixels, default 96."
        }
      },
      "required": []
    }
  },
  {
    "name": "cad_library_share",
    "group": "files",
    "description": "Keep a library object in the app-wide library too, so every project can place it (shared:false stops that; placed copies stay). Only the live app has an app-wide library; elsewhere use cad_library_export / cad_library_import to carry objects between projects.",
    "parameters": {
      "type": "object",
      "properties": {
        "item": {
          "type": "string"
        },
        "shared": {
          "type": "boolean",
          "description": "Default true."
        }
      },
      "required": [
        "item"
      ]
    }
  },
  {
    "name": "cad_library_export",
    "group": "files",
    "description": "The library objects as JSON (all, or the ones in `items`), to keep or to hand to cad_library_import in another project.",
    "parameters": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": []
    }
  },
  {
    "name": "cad_library_import",
    "group": "files",
    "description": "Add library objects from cad_library_export. An object already here is replaced only by a newer one (its linked copies follow).",
    "parameters": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      },
      "required": [
        "items"
      ]
    }
  },
  {
    "name": "cad_library_rename",
    "group": "files",
    "description": "Rename a library object.",
    "parameters": {
      "type": "object",
      "properties": {
        "item": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "item",
        "name"
      ]
    }
  },
  {
    "name": "cad_library_remove",
    "group": "files",
    "description": "Remove a library object. Its placed copies stay as ordinary shapes.",
    "parameters": {
      "type": "object",
      "properties": {
        "item": {
          "type": "string"
        }
      },
      "required": [
        "item"
      ]
    }
  },
  {
    "name": "cad_group_remove",
    "group": "files",
    "description": "Dissolve one group (its shapes and inner groups stay, moving up into the group around it).",
    "parameters": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        }
      },
      "required": [
        "group"
      ]
    }
  },
  {
    "name": "cad_shapes_join",
    "group": "files",
    "description": "Join shapes into one solid: outlines are united wherever they overlap or touch, each keeping its own height and elevation. Bevels on the inputs are not kept.",
    "parameters": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        }
      },
      "required": [
        "ids"
      ]
    }
  },
  {
    "name": "cad_shapes_subtract",
    "group": "files",
    "description": "Cut the cutters out of the \"from\" shapes where they overlap in height (the cutters are used up). A short cutter leaves a slab above and below.",
    "parameters": {
      "type": "object",
      "properties": {
        "from": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        },
        "cutters": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Shape ids."
        }
      },
      "required": [
        "from",
        "cutters"
      ]
    }
  },
  {
    "name": "cad_repeat_set",
    "group": "files",
    "description": "Make (or change) a live repeat: copies of a shape equally spaced along a straight or curved path, or around a circle. The copies follow the shape: edit the source and all of them update. count includes the original. Path: give \"end\", or \"direction\" (degrees) and \"gap\"; \"bend\" curves it. Around: \"center\" of the circle. Call again with the same id to change the repeat.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The shape to repeat."
        },
        "kind": {
          "type": "string",
          "enum": [
            "path",
            "around"
          ]
        },
        "count": {
          "type": "integer"
        },
        "gap": {
          "type": "number",
          "description": "Distance between neighbours along the path, mm."
        },
        "end": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "A point on the ground plane, mm."
        },
        "direction": {
          "type": "number"
        },
        "bend": {
          "oneOf": [
            {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number"
                },
                "y": {
                  "type": "number"
                }
              },
              "required": [
                "x",
                "y"
              ],
              "description": "A point on the ground plane, mm."
            },
            {
              "type": "null"
            }
          ]
        },
        "center": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "description": "A point on the ground plane, mm."
        },
        "follow": {
          "type": "boolean",
          "description": "Turn each copy to face along the path."
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_repeat_remove",
    "group": "files",
    "description": "Let go of a live repeat: its copies stay as ordinary shapes you can edit one by one.",
    "parameters": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "cad_doc_get",
    "group": "files",
    "description": "The whole document as JSON (shapes, groups, repeats): save it, or hand it back to cad_doc_set later.",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "cad_doc_set",
    "group": "files",
    "description": "Replace the whole model with a document from cad_doc_get.",
    "parameters": {
      "type": "object",
      "properties": {
        "doc": {
          "type": "object"
        }
      },
      "required": [
        "doc"
      ]
    }
  },
  {
    "name": "cad_doc_clear",
    "group": "files",
    "description": "Remove every shape.",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "cad_history_undo",
    "group": "files",
    "description": "Undo the last change.",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "cad_history_redo",
    "group": "files",
    "description": "Redo the last undone change.",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "cad_export",
    "group": "files",
    "description": "Export the visible shapes. format \"stl\" (binary, Z-up), \"glb\" (binary glTF for game engines: metres, Y-up, keeps colours and materials), \"obj\" (text) or \"json\" (the document). glb options: scale (output metres per scene mm, default 0.001) and pivot (\"scene\" as placed, \"asset\" centred on the ground, \"shape\" one pivot per shape at the centre of its base). The file is saved as an artifact the person can download from the thread, and the reply names it; pass name to choose the file name.",
    "parameters": {
      "type": "object",
      "properties": {
        "format": {
          "type": "string",
          "enum": [
            "stl",
            "glb",
            "obj",
            "json"
          ]
        },
        "scale": {
          "type": "number"
        },
        "pivot": {
          "type": "string",
          "enum": [
            "scene",
            "asset",
            "shape"
          ]
        },
        "name": {
          "type": "string",
          "description": "File name, without or with the extension."
        }
      },
      "required": [
        "format"
      ]
    }
  },
  {
    "name": "cad_batch",
    "group": "files",
    "description": "Run several commands in order. By default all-or-nothing: if one fails nothing is changed and you are told which. Later commands can use ids returned earlier only by calling again, so give shapes explicit names and look them up with cad_scene_get, or use ids from the response. Inside commands, name a tool as shape_add or cad_shape_add; both work.",
    "parameters": {
      "type": "object",
      "properties": {
        "commands": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "tool": {
                "type": "string"
              },
              "args": {
                "type": "object"
              }
            },
            "required": [
              "tool"
            ]
          }
        },
        "atomic": {
          "type": "boolean"
        }
      },
      "required": [
        "commands"
      ]
    }
  }
] as ToolSpec[];
